elixir-tools/elixir-tools.nvim

.github/workflows/ci.yml, README.md, lua/elixir/init.lua
With `vim.lsp.start` and the new `vim.fs` utilities, we can drop the dep
on nvim-lspconfig.
Closes #5
=> feat: no longer require nvim-lspconfig

.github/workflows/ci.yml, README.md, lua/elixir/init.lua
This reverts commit 112804679eebe3609cdd68484a4958b8e5781602.
Fixes #29
=> Revert "feat: no longer require nvim-lspconfig (#27)"

README.md, lua/elixir/init.lua, lua/elixir/projectionist/init.lua
Provides vim-projectionist heuristics for the following file types, including templates to create the files if they don't exist.
- Elixir files
- Phoenix Views
- Phoenix Controllers
- Phoenix Channels
- Wallaby/Hound Feature tests
=> Support for vim-projectionist

README.md, lua/elixir/language_server/init.lua
This patch allows you to use `cmd = "path"` in the settings so that you can point to an already installed `elixir-ls`. This is useful is you manage those yourself or if you are for example hacking on `elixir-ls` improvements in your local development environment.
=> Allow locally installed elixir-ls

README.md
As discussed in #51. This just add a `<space>` to the existing examples, that should not clash with anything in (Neo)Vim’s default set-up.
=> Conflict-free example bindings

lua/elixir/credo/init.lua
=> fix: only start credo if it finds a mix.exs with credo in it

README.md
Found via `typos --format brief`
=> chore: fix typo, langauge -> language

queries/elixir/injections.scm
- highlight the template argument of `EEx.function_from_string` as `eex`
- highlight the argument of `execute` as `sql` (Ecto migrations).
Closes #9
=> feat(treesitter): injections

lua/elixir/projectionist/init.lua
Hello!
This adds the `live` folder to projectionist, though with Phoenix 1.7 lurking around the corner some other additions are likely useful with the modified directory structure.
=> Add liveview folder locations to Projectionist

lua/elixir/elixirls/init.lua
we are running `elixir --version` every single time we attach to an elixir filetype (on FileType), so
we need to schedule the callback for later as to not slow down BufEnter.
Fixes #59
---
I tested this using @NJichev's dotfiles using `NVIM_APPNAME nj-nvim nvim path/to/file.ex` (with his dotfiles cloned to `~/.config/nj-nvim`).
I tested before the change, after the change, and not including the plug-in at all (completely uninstalled it). 
@NJichev, please try out this branch and confirm it works for you and i'll merge.
<details><summary>--startuptime before.txt</summary>
<p>
```
times in msec
clock   self+sourced   self:  sourced script
clock   elapsed:              other lines
000.005  000.005: --- NVIM STARTING ---
000.042  000.037: event init
000.100  000.059: early init
000.292 …
```
=> fix: improve BufEnter performance

lua/elixir/elixirls/version.lua, lua/elixir/health.lua
=> feat: healthcheck

lua/elixir/utils.lua, tests/fixtures/project_a/lib/module.ex, tests/fixtures/project_a/mix.exs, tests/fixtures/project_b/apps/app_a/lib/module.ex, tests/fixtures/project_b/apps/app_a/mix.exs, tests/fixtures/project_b/mix.exs, tests/utils_spec.lua
This fixes umbrella path detection. Currently, `maybe_umbrella_path` is always the same as `child_or_root_path` because of how `vim.fs.find` works.
So this change kind of restores the logic that existed before removing [lspconfig dep](https://github.com/elixir-tools/elixir-tools.nvim/commit/aa75df6f1aa7bcccf8453c1d432bd5a7ebf682ec#diff-3d47136a879de930f74561d8e082d113c20cca7030680548d8c1bce9c0636ed1L26)
It also removes the logic that detects if the umbrella path contains the dir `apps`. This was because this path could be set to another name in `mix. exs` with `:apps_path,` and maybe it is redundant checking for this when we found the `mix. exs` in a parent dir. But this is a suggestion, and I may be missing something.
=> Fix umbrella app detection

README.md
This also seems to be present in [doc/elixir-tools.nvim.txt](https://github.com/jordelver/elixir-tools.nvim/blob/main/doc/elixir-tools.nvim.txt) but I think that is autogenerated?
=> docs: Correct flag used to enable elixirls and credo

README.md
This is incomplete but a first pass at putting down information on how to use Projectionist within an Elixir project.
=> Add Projectionist info to README

lua/elixir/projectionist/init.lua, tests/projectionist_spec.lua
From what I can tell the JSON view controller can be fairly light and doesn't have the same level of structure as the HTML view controller, but I've added it as well as a Live Component projection!
=> Add Projections for LiveComponent and JSON View Controllers

lua/elixir/init.lua, lua/elixir/utils.lua, tests/utils_spec.lua
Currently, if you attempt to start elixir-tools when offline, this error is generated:
```
Failed to run `config` for elixir.nvim
.../.local/share/nvim/lazy/elixir.nvim/lua/elixir/utils.lua:30: Expected value but found T_END at character 1
- /elixir.nvim/lua/elixir/utils.lua:30 _in_ **latest_release**
- /elixir.nvim/lua/elixir/init.lua:44 _in_ **setup**
- ~/.config/nvim/lua/custom/plugins.lua:288 _in_ **config**
- ~/brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:22
- ~/brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:21
Press ENTER or type command to continue
```
With this change, if you attempt to start elixir-tools when offline, the following messages will instead be printed to the status line:
```
Failed request to Github to fetch version information for latest …
```
=> Gracefully handle latest_release check when offline

lua/elixir/utils.lua
elixir-tools.nvim fails to start if the latest version check fails with a non-200 status code (which happens in cases of a rate limit being reached)
For full description see https://github.com/elixir-tools/elixir-tools.nvim/issues/150
For additional context this was happening to me when I was on a VPN. Since the unauthenticated rate limit relies on IP address, and there are many users on that server, I hit the limit of 60 reqs per hour. This can also happen to someone tweaking their config and re-opening NeoVim a bunch of times.
This PR does two things:
- use the `--fail` switch in the `curl` command that checks the latest version.
This makes the command return a non-zero status if the response status is not
2xx.
- change the message so that it includes a note about a potential failure of …
=> fix: elixir-tools fails to load when latest version check fails

lua/elixir/credo/init.lua, lua/elixir/nextls/init.lua
As for pure mix projects we don't have a mix.lock then the plugin needs another way to know that it's a elixir project to spin up lsp server
=> fix: activate nextls when it detects a mix.exs file

README.md, lua/elixir/nextls/init.lua
feat(nextls): init options
Next LS has support for passing configuring the default MIX_ENV and
MIX_TARGET of your project's runtime, and are accepted as init_options
=> feat(nextls): init options

lua/elixir/utils.lua
This fixes the issue I encountered in #172 on my end at least, `vim.fn` has no docs whatsoever so I had to scour other plugins to figure out how to use it:(\
Closes #172
=> fix: receive correct json responses from curl

lua/elixir/iter/init.lua, lua/elixir/nextls/init.lua
This patch has a dependency on the https://github.com/mhanberg/workspace-folders.nvim plugin.
To try out the behavior, install that plugin and create a `.code-workspace` file that describes your multi-root workspace (or mono repo as most call it), in the root of your mono repo.
If your monorepo is called "money-factory-io", with the folders "crypto", "ai-chat-app", and "drop-shipping-cms", your `code-workspace` would be named `money-factory-io.code-workspace` and look like:
```json
{
"folders": [
{"path": "crypto"},
{"path": "ai-chat-app"},
{"path": "drop-shipping-cms"},
]
}
```
=> feat(nextls): multi-root workspaces

bin/compile
Release mix task has been deprecated for some time and fails to work with Elixir v1.16. The recommended mix task is release2
=> fix: compile ElixirLS with Elixir v1.16

README.md, lua/elixir/init.lua
Refactors the workspace commands a bit as well
=> feat: add refactor alias command

.github/workflows/ci.yml, README.md, justfile, lua/elixir/init.lua, lua/elixir/projectionist/init.lua, tests/projectionist_spec.lua
> Why are we considering this change
Some projects are structured differently (I inherited a codebase that doesn't follow community conventions regarding directory structure).
If I try to overwrite the `projectionist_heuristics`, and the plugin is loaded after my changes, it wipes them out.
It would be great if there was a way to disable the projectionist integration for those of us who need to extend it.
> A high level summary of what changed, including any important notes the reviewer should know
Main changes:
- adds a new user setting for disabling the projectionist integration
- This change leaves the existing behavior of enabling it by default to prevent a breaking change for users.
Ancillary changes:
- Corrected a breaking change for nvim-test that broke the tests
- See …
=> feat(projectionist): allow disabling the projectionist integration

lua/elixir/elixirls/download.lua
I found it helpful to print the repo in the error message. It makes it easier to debug and fix a broken configuration.
=> fix: print elixirls repo if it fails to clone

lua/elixir/elixirls/download.lua
Help print more useful information when troubleshooting a broken git clone.
=> fix: print dest directory if it fails to clone
